// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Move_Town_Precise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_Town_Precise));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090142410_Move_Town_Precise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
