using System;
using Lte.Domain.Common.Wireless.Alarm;

namespace Lte.Domain.Common.Wireless
{
    public static class WirelessPublic
    {
        public static readonly Tuple<AlarmType, string>[] AlarmTypeHuaweiList =
        {
            new Tuple<AlarmType, string>(AlarmType.BbuCpriBad, "BBU CPRI光接口性能恶化告警"), 
            new Tuple<AlarmType, string>(AlarmType.BbuCpriLost, "BBU CPRI光模块/电接口不在位告警"),
            new Tuple<AlarmType, string>(AlarmType.BbuCpriBad, "BBU CPRI光模块故障告警"), 
            new Tuple<AlarmType, string>(AlarmType.BbuCpriInterface, "BBU CPRI接口异常告警"),
            new Tuple<AlarmType, string>(AlarmType.BbuCpriLine, "BBU CPRI线速率协商异常告警"),
            new Tuple<AlarmType, string>(AlarmType.BbuBoard, "BBU单板维护链路异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.BbuFan, "BBU风扇堵转告警"), 
            new Tuple<AlarmType, string>(AlarmType.FiberModule, "BBU光模块收发异常告警"),
            new Tuple<AlarmType, string>(AlarmType.BbuDcOutput, "BBU直流输出异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.LicenseExpired, "License Feature进入保活期告警"), 
            new Tuple<AlarmType, string>(AlarmType.LicenseConfig, "License试运行告警"), 
            new Tuple<AlarmType, string>(AlarmType.OsmuOss, "OSMU单板与OSS心跳异常"), 
            new Tuple<AlarmType, string>(AlarmType.RruCascade, "RRU组网级数与配置不一致告警"), 
            new Tuple<AlarmType, string>(AlarmType.RssiProblem, "RSSI值过高告警"),
            new Tuple<AlarmType, string>(AlarmType.S1UserPlane, "S1接口故障告警"),
            new Tuple<AlarmType, string>(AlarmType.S1Broken, "SCTP链路故障告警"),
            new Tuple<AlarmType, string>(AlarmType.VcsService, "VCS服务未启动"), 
            new Tuple<AlarmType, string>(AlarmType.X2UserPlane, "X2接口故障告警"),
            new Tuple<AlarmType, string>(AlarmType.SecurePassword, "安全管理员组用户修改其他用户密码告警"), 
            new Tuple<AlarmType, string>(AlarmType.CanbusCommunication, "板间CANBUS通信异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.VersionBack, "版本自动回退告警"), 
            new Tuple<AlarmType, string>(AlarmType.FiberReceiver, "传输光接口异常告警"),
            new Tuple<AlarmType, string>(AlarmType.FiberModule, "传输光模块不在位告警"), 
            new Tuple<AlarmType, string>(AlarmType.DiskUsage, "磁盘占用率过高告警"), 
            new Tuple<AlarmType, string>(AlarmType.DiskUsage, "磁盘占用率过高告警(次要)"),
            new Tuple<AlarmType, string>(AlarmType.DiskUsage, "磁盘占用率过高告警(紧急)"),
            new Tuple<AlarmType, string>(AlarmType.DiskUsage, "磁盘占用率过高告警(提示)"),
            new Tuple<AlarmType, string>(AlarmType.DiskUsage, "磁盘占用率过高告警(重要)"),
            new Tuple<AlarmType, string>(AlarmType.BoardInexist, "单板不在位告警"), 
            new Tuple<AlarmType, string>(AlarmType.BoardNoConfig, "单板类型和配置不匹配告警"), 
            new Tuple<AlarmType, string>(AlarmType.BoardIncreament, "单板软件自动增补失败告警"), 
            new Tuple<AlarmType, string>(AlarmType.BoardClock, "单板时钟输入异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.BoardTemperature, "单板温度异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.BoardHardware, "单板硬件故障告警"), 
            new Tuple<AlarmType, string>(AlarmType.LoginError, "登录尝试次数达到最大值告警"),
            new Tuple<AlarmType, string>(AlarmType.EletricAntennaMoter, "电调天线马达故障告警"), 
            new Tuple<AlarmType, string>(AlarmType.ElectricAntennaData, "电调天线数据丢失告警"), 
            new Tuple<AlarmType, string>(AlarmType.EletricAntenna, "电调天线未校准告警"),
            new Tuple<AlarmType, string>(AlarmType.ElectricAntennaData, "电调天线运行数据异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.AlarmReportJam, "告警上报缓冲拥塞告警"), 
            new Tuple<AlarmType, string>(AlarmType.RackConfig, "机框类型配置与实际不一致告警"), 
            new Tuple<AlarmType, string>(AlarmType.S1Broken, "基站控制面传输中断告警"),
            new Tuple<AlarmType, string>(AlarmType.SoftwareAbnormal, "配置数据不一致告警"),
            new Tuple<AlarmType, string>(AlarmType.LicenseConfig, "配置数据超出License限制告警"), 
            new Tuple<AlarmType, string>(AlarmType.ConfigFile, "配置文件损坏告警"), 
            new Tuple<AlarmType, string>(AlarmType.TaskFail, "任务执行失败告警"),
            new Tuple<AlarmType, string>(AlarmType.RfAld, "射频单元ALD电流异常告警"),
            new Tuple<AlarmType, string>(AlarmType.RfAld, "射频单元ALD开关配置不匹配告警"), 
            new Tuple<AlarmType, string>(AlarmType.RruCpriInterface, "射频单元CPRI接口异常告警"),
            new Tuple<AlarmType, string>(AlarmType.RfTransmit, "射频单元发射通道增益异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.RfMode, "射频单元工作模式与单板能力不匹配告警"), 
            new Tuple<AlarmType, string>(AlarmType.RruInterfacePerformance, "射频单元光接口性能恶化告警"),
            new Tuple<AlarmType, string>(AlarmType.RruPowerDown, "射频单元交流掉电告警"),
            new Tuple<AlarmType, string>(AlarmType.RruRtwpUnbalance, "射频单元接收通道RTWP/RSSI不平衡告警"),
            new Tuple<AlarmType, string>(AlarmType.RruRtwp, "射频单元接收通道RTWP/RSSI过低告警"),
            new Tuple<AlarmType, string>(AlarmType.RruClock, "射频单元时钟异常告警"),
            new Tuple<AlarmType, string>(AlarmType.RfInputSource, "射频单元输入电源能力不足告警"), 
            new Tuple<AlarmType, string>(AlarmType.RruOmcLink, "射频单元维护链路异常告警"),
            new Tuple<AlarmType, string>(AlarmType.RruBroken, "射频单元硬件故障告警"),
            new Tuple<AlarmType, string>(AlarmType.RruRuntime, "射频单元运行时拓扑异常告警"), 
            new Tuple<AlarmType, string>(AlarmType.RruDc, "射频单元直流掉电告警"), 
            new Tuple<AlarmType, string>(AlarmType.VswrProblem, "射频单元驻波告警"),
            new Tuple<AlarmType, string>(AlarmType.SntpFail, "时间同步失败告警"),
            new Tuple<AlarmType, string>(AlarmType.ClockReference, "时钟参考源异常告警"),
            new Tuple<AlarmType, string>(AlarmType.Database, "数据库占用率过高告警(提示)"),
            new Tuple<AlarmType, string>(AlarmType.Database, "数据库占用率过高告警(次要)"),
            new Tuple<AlarmType, string>(AlarmType.AntennaLink, "天线设备维护链路异常告警"),
            new Tuple<AlarmType, string>(AlarmType.AntennaHardware, "天线设备硬件故障告警"), 
            new Tuple<AlarmType, string>(AlarmType.LicenseConfig, "网管License超限告警"), 
            new Tuple<AlarmType, string>(AlarmType.OuterApparatus, "网管服务异常退出告警"),
            new Tuple<AlarmType, string>(AlarmType.LinkBroken, "网元连接中断"),
            new Tuple<AlarmType, string>(AlarmType.NeVersion, "网元适配层版本不匹配"), 
            new Tuple<AlarmType, string>(AlarmType.LicenseExpired, "系统超出License容量限制告警"), 
            new Tuple<AlarmType, string>(AlarmType.NoClock, "系统时钟不可用告警"),
            new Tuple<AlarmType, string>(AlarmType.PciCrack, "小区PCI冲突告警"),
            new Tuple<AlarmType, string>(AlarmType.CellDown, "小区不可用告警"),
            new Tuple<AlarmType, string>(AlarmType.BadPerformance, "小区服务能力下降告警"),
            new Tuple<AlarmType, string>(AlarmType.SinrUnbalance, "小区接收通道干扰噪声功率不平衡告警"), 
            new Tuple<AlarmType, string>(AlarmType.AnalogLoad, "小区模拟负载启动告警"),
            new Tuple<AlarmType, string>(AlarmType.ReconfigurationFailure, "小区重配置失败告警"), 
            new Tuple<AlarmType, string>(AlarmType.StarUnlocked, "星卡天线故障告警"),
            new Tuple<AlarmType, string>(AlarmType.DatabaseDelay, "性能数据库剩余空间不足"),
            new Tuple<AlarmType, string>(AlarmType.EthernetBroken, "以太网链路故障告警"),
            new Tuple<AlarmType, string>(AlarmType.TrunkProblem, "用户面承载链路故障告警"),
            new Tuple<AlarmType, string>(AlarmType.UserPlane, "用户面承载链路故障告警"),
            new Tuple<AlarmType, string>(AlarmType.RemoteOmc, "远程维护通道故障告警"),
        };
    }
}