// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_InterferenceMatrix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_InterferenceMatrix));
        
        string IMigrationMetadata.Id
        {
            get { return "201709200949261_Change_InterferenceMatrix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
