// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Construct_Dt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Construct_Dt));
        
        string IMigrationMetadata.Id
        {
            get { return "201810051535544_Construct_Dt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
